### ISSUE TITLE
Are you update /etc/security/limits.conf ?

### ISSUE THREAD

**Issue by VictorTrapenok** [kostyrevaa/ansible-role-highload#1]
I was use this role, and after reboot command ulimit -n show 1024
I think will be good if you add to this role changing file /etc/security/limits.conf for fix this.

**Comment by kostyrev** [comment]
It's no surprise that you see 1024 because this role does not configure those limits.  
For that purposes I can recommend [this](https://github.com/Oefenweb/ansible-limits) role.

**Comment by VictorTrapenok** [comment]
Thank you very much!
